spring.application.name=api-gateway
server.port=8088

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
eureka.instance.prefer-ip-address=true

# explicit routes (useful for path stability)
spring.cloud.gateway.routes[0].id=catalog
spring.cloud.gateway.routes[0].uri=lb://catalog-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/catalog/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=user
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=webapp
spring.cloud.gateway.routes[2].uri=lb://webapp
spring.cloud.gateway.routes[2].predicates[0]=Path=/**

management.endpoints.web.exposure.include=health,info

# JWT validation shared with user-service
security.jwt.secret=dev-secret-key-should-be-long-and-random-256bit-min
